### ISSUE TITLE
 "Space War" empty list happens again and it's unresolvable at my end

### ISSUE THREAD

**Issue by Ylem-One** [gibbed/SteamAchievementManager#368]
The well-known "Space War" empty game list in SAMPicker is back and even when I try to add the game manually, typing its App ID in the ""Add game" field, the game does not appear on the list, or it appears completely empty - without an thumbnail image and without any listed achievements (empty list). Then, it disappears again and "Space War" is again the only thing on the list. Therefore, I'm totally unable to solve it at my end as re-installing the app doesn't fix it either.

**Comment by gibbed** [comment]
The empty game list issue should be fixed at this point.

For your issue adding games, just to make sure, you clicked "Add Game"?

**Comment by Ylem-One** [comment]
Well, it's not fixed, unfortunately. Tried everything I could think of.

And yes, as I add games, I click "Add Game". I checked with various games, and any game of any App-ID doesn't appear on the list at all.
